DELETE FROM rsvps;
ALTER SEQUENCE rsvps_id_seq RESTART WITH 1;

INSERT INTO rsvps (first_name, last_name) VALUES
('Branko', 'Bjelic'),
('Jadranka', 'Bjelic'),
('Frederick', 'Faller'),
('Janine', 'von Collas'),
('Tabea', 'Huber'),
('Jan', 'Schneider'),
('Maik', 'Henrich'),
('Birgit', ''),
('Isabel', 'Schäfer'),
('Eric', 'Schäfer'),
('Alexandra', 'Rachow'),
('Simone', 'Fiedler'),
('Zoran', 'Bijelic'),
('Cuba', 'Bijelic'),
('Leon', 'Plumpe'),
('Toni', 'Vitt'),
('Yvonne', 'Jungjohann'),
('Dirk', 'Jungjohann'),
('Norbert', 'Jungjohann'),
('Cassie', 'Jungjohann'),
('Jonah', 'Alsheimer'),
('Melina', 'Siegl'),
('Karsten', 'Henrich'),
('Iwona', 'Henrich'),
('Hendrik', 'Gruber'),
('Carla', ''),
('Elena', 'Ilievska-Jovanovic'),
('Dusan', 'Jovanovic'),
('Karolina', 'Maliewska'),
('Jannick', 'Arnold'),
('Djordje', 'Bijelic'),
('Brankica', 'Bijelic'),
('Natalie', 'Vollmer'),
('Philip', ''),
('Niko', 'Bjelic'),
('Nadja', 'Bjelic'),
('Frauke', 'Jungjohann'),
('Klaus', 'Hundeborn'),
('Marcel', 'Henrich'),
('Lara', 'Jansen'),
('David', 'Witt'),
('Isabel', 'Witt'),
('Nina', 'Hofmann'),
('Nico', 'Nakowitsch'),
('Jordi', 'Aparicio Rodriguez'),
('Debora', 'Urgesi'),
('Tessa', 'Henrich-Scheufele'),
('Oliver', 'Scheufele'),
('Leon', 'Rosenzweig'),
('Daniela', 'Wagner'),
('Sophia', 'Rachow'),
('Joachim', 'Henrich'),
('Chiara', 'Schramm'),
('Merve', 'Sahin'),
('Sandra', 'Huber'),
('Marvin', 'Henrich'),
('Henrik', 'Losch'),
('Corwin', 'Jungjohann'),
('Alina', 'Grigorjan');

DELETE FROM Couples;
ALTER SEQUENCE couples_id_seq RESTART WITH 1;

INSERT INTO couples (id, person1_first_name, person1_last_name, person2_first_name, person2_last_name) VALUES
(1, 'Branko', 'Bjelic', 'Jadranka', 'Bjelic'),
(10, 'Frederick', 'Faller', 'Janine', 'von Collas'),
(11, 'Tabea', 'Huber', 'Jan', 'Schneider'),
(12, 'Maik', 'Henrich', 'Birgit', ''),
(13, 'Isabel', 'Schäfer', 'Eric', 'Schäfer'),
(14, 'Alexandra', 'Rachow', 'Simone', 'Fiedler'),
(15, 'Zoran', 'Bijelic', 'Cuba', 'Bijelic'),
(16, 'Leon', 'Plumpe', 'Toni', 'Vitt'),
(17, 'Yvonne', 'Jungjohann', 'Dirk', 'Jungjohann'),
(18, 'Norbert', 'Jungjohann', 'Cassie', 'Jungjohann'),
(19, 'Jonah', 'Alsheimer', 'Melina', 'Siegl'),
(20, 'Karsten', 'Henrich', 'Iwona', 'Henrich'),
(21, 'Elena', 'Ilievska-Jovanovic', 'Dusan', 'Jovanovic'),
(22, 'Karolina', 'Maliewska', 'Jannick', 'Arnold'),
(23, 'Djordje', 'Bijelic', 'Brankica', 'Bijelic'),
(24, 'Natalie', 'Vollmer', 'Philip', ''),
(25, 'Niko', 'Bjelic', 'Nadja', 'Bjelic'),
(3, 'Frauke', 'Jungjohann', 'Klaus', 'Hundeborn'),
(4, 'Marcel', 'Henrich', 'Lara', 'Jansen'),
(5, 'David', 'Witt', 'Isabel', 'Witt'),
(6, 'Nina', 'Hofmann', 'Nico', 'Nakowitsch'),
(7, 'Jordi', 'Aparicio Rodriguez', 'Debora', 'Urgesi'),
(8, 'Tessa', 'Henrich-Scheufele', 'Oliver', 'Scheufele'),
(9, 'Leon', 'Rosenzweig', 'Daniela', 'Wagner');